Repository honeydipper/honeydipper, pull requests merged in 2019-02, with the labels that each got.

#44 Use (in)valid example domains
  docs/workflow.md
Labels: docs

#42 Update badge in README
  README.md
Labels: docs

#49 fix(service): issue #34 daemon crashing when operator call undefined driver
  internal/service/operator.go
  internal/service/service.go
Labels: priority: p2

#59 docs(installation): migrating to honeydipper repo and more
  docs/INSTALL.md
  docs/README.md
  docs/configuration.md
  docs/developer.md
  docs/howtos/enable_encryption.md
  docs/howtos/reload_on_push.md
  docs/howtos/setup_local.md
Labels: docs

#62 fix(kubernetes): recycling deployment by killing the correct replicaset
  drivers/cmd/kubernetes/main.go
Labels: blocked
